//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 08:17:05 下午 CST
//


package com.ectrip.ticket.cyt.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 【畅游通提供】【订单】核销（verifyConsume）
 * 赋初始值：已完成！
 * <p>Java class for VerifyConsumeRequestBody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VerifyConsumeRequestBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMRequestDataSchema}RequestBody">
 *       &lt;sequence>
 *         &lt;element name="orderInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="otaOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cytOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="posid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="verifyConsumeInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerifyConsumeRequestBody", propOrder = {
        "orderInfo"
})
public class VerifyConsumeRequestBody
        extends RequestBody
{

    @XmlElement(required = true)
    protected VerifyConsumeRequestBody.OrderInfo orderInfo;

    public VerifyConsumeRequestBody() {
        super();
        this.orderInfo = new VerifyConsumeRequestBody.OrderInfo();
    }

    /**
     * Gets the value of the orderInfo property.
     *
     * @return
     *     possible object is
     *     {@link VerifyConsumeRequestBody.OrderInfo }
     *
     */
    public VerifyConsumeRequestBody.OrderInfo getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link VerifyConsumeRequestBody.OrderInfo }
     *
     */
    public void setOrderInfo(VerifyConsumeRequestBody.OrderInfo value) {
        this.orderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="otaOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cytOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="posid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="verifyConsumeInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "otaOrderId",
            "cytOrderId",
            "orderQuantity",
            "token",
            "posid",
            "verifyConsumeInfo"
    })
    public static class OrderInfo {

        @XmlElement(required = true)
        protected String otaOrderId;
        @XmlElement(required = true)
        protected String cytOrderId;
        @XmlElement(required = true)
        protected String orderQuantity;
        @XmlElement(required = true)
        protected String token;
        @XmlElement(required = true)
        protected String posid;
        @XmlElement(required = true)
        protected String verifyConsumeInfo;

        public OrderInfo() {
            super();
            this.otaOrderId = "";
            this.cytOrderId = "";
            this.orderQuantity = "";
            this.token = "";
            this.posid = "";
            this.verifyConsumeInfo = "";
        }

        /**
         * Gets the value of the otaOrderId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOtaOrderId() {
            return otaOrderId;
        }

        /**
         * Sets the value of the otaOrderId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOtaOrderId(String value) {
            this.otaOrderId = value;
        }

        /**
         * Gets the value of the cytOrderId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCytOrderId() {
            return cytOrderId;
        }

        /**
         * Sets the value of the cytOrderId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCytOrderId(String value) {
            this.cytOrderId = value;
        }

        /**
         * Gets the value of the orderQuantity property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOrderQuantity() {
            return orderQuantity;
        }

        /**
         * Sets the value of the orderQuantity property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOrderQuantity(String value) {
            this.orderQuantity = value;
        }

        /**
         * Gets the value of the token property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getToken() {
            return token;
        }

        /**
         * Sets the value of the token property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setToken(String value) {
            this.token = value;
        }

        /**
         * Gets the value of the posid property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPosid() {
            return posid;
        }

        /**
         * Sets the value of the posid property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPosid(String value) {
            this.posid = value;
        }

        /**
         * Gets the value of the verifyConsumeInfo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVerifyConsumeInfo() {
            return verifyConsumeInfo;
        }

        /**
         * Sets the value of the verifyConsumeInfo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVerifyConsumeInfo(String value) {
            this.verifyConsumeInfo = value;
        }

    }

}
