package com.ectrip.ticket.cyt.model.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.11 at 09:03:41 AM CST 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 【OTO提供】【订单】创建复合订单（createComplexOrder）
 *
 * <p>Java class for CreateComplexOrderResponseBody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateComplexOrderResponseBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMResponseSchema}ResponseBody">
 *       &lt;sequence>
 *         &lt;element name="orderInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="returnInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateComplexOrderResponseBody", propOrder = {
        "orderInfo"
})
public class CreateComplexOrderResponseBody
        extends ResponseBody
{

    @XmlElement(required = true)
    protected OrderInfo orderInfo;

    public CreateComplexOrderResponseBody() {
        super();
        this.orderInfo = new OrderInfo();
    }

    /**
     * Gets the value of the orderInfo property.
     *
     * @return
     *     possible object is
     *     {@link CreateComplexOrderResponseBody.OrderInfo }
     *
     */
    public OrderInfo getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link CreateComplexOrderResponseBody.OrderInfo }
     *
     */
    public void setOrderInfo(OrderInfo value) {
        this.orderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="returnInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note7" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note8" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "partnerorderId",
            "orderStatus",
            "returnInfo"
    })
    public static class OrderInfo {

        @XmlElement(required = true)
        protected String partnerorderId;
        @XmlElement(required = true)
        protected String orderStatus;
        @XmlElement(required = true)
        protected ReturnInfo returnInfo;

        public OrderInfo() {
            super();
            this.partnerorderId = "";
            this.orderStatus = "";
            this.returnInfo = new ReturnInfo();
        }

        /**
         * Gets the value of the partnerorderId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPartnerorderId() {
            return partnerorderId;
        }

        /**
         * Sets the value of the partnerorderId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPartnerorderId(String value) {
            this.partnerorderId = value;
        }

        /**
         * Gets the value of the orderStatus property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOrderStatus() {
            return orderStatus;
        }

        /**
         * Sets the value of the orderStatus property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOrderStatus(String value) {
            this.orderStatus = value;
        }

        /**
         * Gets the value of the returnInfo property.
         *
         * @return
         *     possible object is
         *     {@link CreateComplexOrderResponseBody.OrderInfo.ReturnInfo }
         *
         */
        public ReturnInfo getReturnInfo() {
            return returnInfo;
        }

        /**
         * Sets the value of the returnInfo property.
         *
         * @param value
         *     allowed object is
         *     {@link CreateComplexOrderResponseBody.OrderInfo.ReturnInfo }
         *
         */
        public void setReturnInfo(ReturnInfo value) {
            this.returnInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note7" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note8" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "note1",
                "note2",
                "note3",
                "note4",
                "note5",
                "note6",
                "note7",
                "note8"
        })
        public static class ReturnInfo {

            @XmlElement(required = true)
            protected String note1;
            @XmlElement(required = true)
            protected String note2;
            @XmlElement(required = true)
            protected String note3;
            @XmlElement(required = true)
            protected String note4;
            @XmlElement(required = true)
            protected String note5;
            @XmlElement(required = true)
            protected String note6;
            @XmlElement(required = true)
            protected String note7;
            @XmlElement(required = true)
            protected String note8;

            public ReturnInfo() {
                super();
                this.note1 = "";
                this.note2 = "";
                this.note3 = "";
                this.note4 = "";
                this.note5 = "";
                this.note6 = "";
                this.note7 = "";
                this.note8 = "";
            }

            /**
             * Gets the value of the note1 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote1() {
                return note1;
            }

            /**
             * Sets the value of the note1 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote1(String value) {
                this.note1 = value;
            }

            /**
             * Gets the value of the note2 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote2() {
                return note2;
            }

            /**
             * Sets the value of the note2 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote2(String value) {
                this.note2 = value;
            }

            /**
             * Gets the value of the note3 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote3() {
                return note3;
            }

            /**
             * Sets the value of the note3 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote3(String value) {
                this.note3 = value;
            }

            /**
             * Gets the value of the note4 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote4() {
                return note4;
            }

            /**
             * Sets the value of the note4 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote4(String value) {
                this.note4 = value;
            }

            /**
             * Gets the value of the note5 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote5() {
                return note5;
            }

            /**
             * Sets the value of the note5 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote5(String value) {
                this.note5 = value;
            }

            /**
             * Gets the value of the note6 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote6() {
                return note6;
            }

            /**
             * Sets the value of the note6 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote6(String value) {
                this.note6 = value.replace("Ectrip", "yilvbao");
            }

            /**
             * Gets the value of the note7 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote7() {
                return note7;
            }

            /**
             * Sets the value of the note7 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote7(String value) {
                this.note7 = value;
            }

            /**
             * Gets the value of the note8 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote8() {
                return note8;
            }

            /**
             * Sets the value of the note8 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote8(String value) {
                this.note8 = value;
            }

        }

    }

}
