package com.ectrip.ec.model.notebook;



/**
 * Notebook generated by MyEclipse - Hibernate Tools
 */

public class Notebook  implements java.io.Serializable {


    // Fields    
	 public final static int ADD = 1;
	 public final static int EDIT = 2;
	 public final static int DELETE = 3;
	 public final static int VIEW = 4;
	 public final static int REPLAY = 5;
	 private int strutsAction;
     private Long noteid;
     private String noteusid;
     private String notecontent;
     private String notedate;
     private String noteip;
     private String renotecontent;
     private String renotedate;
     private String reempid;
     private Long naudit;
     private Long istop;
     private String ntitle;
     private String ntel;
     private String nemail;
     private Long ishf;
     private String ntype;
     private String strntype;
     private int shflg;
     private String flgre;
    // Constructors

    public String getFlgre() {
		return flgre;
	}

	public void setFlgre(String flgre) {
		this.flgre = flgre;
	}

	public String getStrntype() {
		return strntype;
	}

	public void setStrntype(String strntype) {
		this.strntype = strntype;
	}

	public String getNtype() {
		return ntype;
	}

	public void setNtype(String ntype) {
		if(ntype==null || "".equals(ntype) || "5".equals(ntype)){
			setStrntype("����");
		}else if("1".equals("ntype")){
			setStrntype("Ͷ��");
		}else if("2".equals("ntype")){
			setStrntype("�ٱ�");
		}else if("3".equals("ntype")){
			setStrntype("����");
		}else if("4".equals("ntype")){
			setStrntype("����");
		}else{
			setStrntype("����");
		}
		this.ntype = ntype;
	}

	/** default constructor */
    public Notebook() {
    }

	/** minimal constructor */
    public Notebook(Long noteid, String noteusid, String notecontent, String notedate, String noteip) {
        this.noteid = noteid;
        this.noteusid = noteusid;
        this.notecontent = notecontent;
        this.notedate = notedate;
        this.noteip = noteip;
    }
    
    /** full constructor */
    public Notebook(Long noteid, String noteusid, String notecontent, String notedate, String noteip, String renotecontent, String renotedate, String reempid, Long naudit, Long istop, String ntitle, String ntel, String nemail,Long ishf,String ntype) {
        this.noteid = noteid;
        this.noteusid = noteusid;
        this.notecontent = notecontent;
        this.notedate = notedate;
        this.noteip = noteip;
        this.renotecontent = renotecontent;
        this.renotedate = renotedate;
        this.reempid = reempid;
        this.naudit = naudit;
        this.istop = istop;
        this.ntitle = ntitle;
        this.ntel = ntel;
        this.nemail = nemail;
        this.ishf=ishf;
        this.ntype=ntype;
    }

   
    // Property accessors

    public Long getNoteid() {
        return this.noteid;
    }
    
    public void setNoteid(Long noteid) {
        this.noteid = noteid;
    }

    public String getNoteusid() {
        return this.noteusid;
    }
    
    public void setNoteusid(String noteusid) {
        this.noteusid = noteusid;
    }

    public String getNotecontent() {
        return this.notecontent;
    }
    
    public void setNotecontent(String notecontent) {
        this.notecontent = notecontent;
    }

    public String getNotedate() {
        return this.notedate;
    }
    
    public void setNotedate(String notedate) {
        this.notedate = notedate;
    }

    public String getNoteip() {
        return this.noteip;
    }
    
    public void setNoteip(String noteip) {
        this.noteip = noteip;
    }

    public String getRenotecontent() {
        return this.renotecontent;
    }
    
    public void setRenotecontent(String renotecontent) {
        this.renotecontent = renotecontent;
    }

    public String getRenotedate() {
        return this.renotedate;
    }
    
    public void setRenotedate(String renotedate) {
        this.renotedate = renotedate;
    }

    public String getReempid() {
        return this.reempid;
    }
    
    public void setReempid(String reempid) {
        this.reempid = reempid;
    }

    public Long getNaudit() {
        return this.naudit;
    }
    
    public void setNaudit(Long naudit) {
        this.naudit = naudit;
    }

    public Long getIstop() {
        return this.istop;
    }
    
    public void setIstop(Long istop) {
        this.istop = istop;
    }

    public String getNtitle() {
        return this.ntitle;
    }
    
    public void setNtitle(String ntitle) {
        this.ntitle = ntitle;
    }

    public String getNtel() {
        return this.ntel;
    }
    
    public void setNtel(String ntel) {
        this.ntel = ntel;
    }

    public String getNemail() {
        return this.nemail;
    }
    
    public void setNemail(String nemail) {
        this.nemail = nemail;
    }

	public Long getIshf() {
		return ishf;
	}

	public void setIshf(Long ishf) {
		this.ishf = ishf;
	}

	public int getShflg() {
		return shflg;
	}

	public void setShflg(int shflg) {
		this.shflg = shflg;
	}

	public int getStrutsAction() {
		return strutsAction;
	}

	public void setStrutsAction(int strutsAction) {
		this.strutsAction = strutsAction;
	}
   








}