package com.ectrip.ticket.cyt.model.request;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.11 at 09:02:14 AM CST 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 【OTO提供】【订单】创建复合订单（createComplexOrder）
 *
 * <p>Java class for CreateComplexOrderRequestBody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateComplexOrderRequestBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMRequestDataSchema}RequestBody">
 *       &lt;sequence>
 *         &lt;element name="orderInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="otaOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cytOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ticketPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="product">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="visitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="productInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="timeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="areaId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="canrefundpart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="contactPerson">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="visitPerson">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="person" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateComplexOrderRequestBody", propOrder = {
        "orderInfo"
})
public class CreateComplexOrderRequestBody
        extends RequestBody
{

    @XmlElement(required = true)
    protected OrderInfo orderInfo;

    public CreateComplexOrderRequestBody() {
        super();
        this.orderInfo = new CreateComplexOrderRequestBody.OrderInfo();
    }

    /**
     * Gets the value of the orderInfo property.
     *
     * @return
     *     possible object is
     *     {@link CreateComplexOrderRequestBody.OrderInfo }
     *
     */
    public OrderInfo getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link CreateComplexOrderRequestBody.OrderInfo }
     *
     */
    public void setOrderInfo(OrderInfo value) {
        this.orderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="otaOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cytOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ticketPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="product">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="visitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="productInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="timeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="areaId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="canrefundpart" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="contactPerson">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="visitPerson">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="person" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "otaOrderId",
            "cytOrderId",
            "ticketPassword",
            "token",
            "product",
            "productInfo",
            "contactPerson",
            "visitPerson",
            "orderQuantity",
            "orderPrice",
            "orderStatus"
    })
    public static class OrderInfo {

        @XmlElement(required = true)
        protected String otaOrderId;
        @XmlElement(required = true)
        protected String cytOrderId;
        @XmlElement(required = true)
        protected String ticketPassword;
        @XmlElement(required = true)
        protected String token;
        @XmlElement(required = true)
        protected Product product;
        @XmlElement(required = true)
        protected ProductInfo productInfo;
        @XmlElement(required = true)
        protected ContactPerson contactPerson;
        @XmlElement(required = true)
        protected VisitPerson visitPerson;
        @XmlElement(required = true)
        protected String orderQuantity;
        @XmlElement(required = true)
        protected String orderPrice;
        @XmlElement(required = true)
        protected String orderStatus;

        public OrderInfo() {
            super();
            this.otaOrderId = "";
            this.cytOrderId = "";
            this.ticketPassword = "";
            this.token = "";
            this.product = new Product();
            this.productInfo = new ProductInfo();
            this.contactPerson = new ContactPerson();
            this.visitPerson = new VisitPerson();
            this.orderQuantity = "";
            this.orderPrice = "";
            this.orderStatus = "";

        }

        /**
         * Gets the value of the otaOrderId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOtaOrderId() {
            return otaOrderId;
        }

        /**
         * Sets the value of the otaOrderId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOtaOrderId(String value) {
            this.otaOrderId = value;
        }

        /**
         * Gets the value of the cytOrderId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCytOrderId() {
            return cytOrderId;
        }

        /**
         * Sets the value of the cytOrderId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCytOrderId(String value) {
            this.cytOrderId = value;
        }

        /**
         * Gets the value of the ticketPassword property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getTicketPassword() {
            return ticketPassword;
        }

        /**
         * Sets the value of the ticketPassword property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTicketPassword(String value) {
            this.ticketPassword = value;
        }

        /**
         * Gets the value of the token property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getToken() {
            return token;
        }

        /**
         * Sets the value of the token property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setToken(String value) {
            this.token = value;
        }

        /**
         * Gets the value of the product property.
         *
         * @return
         *     possible object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.Product }
         *
         */
        public Product getProduct() {
            return product;
        }

        /**
         * Sets the value of the product property.
         *
         * @param value
         *     allowed object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.Product }
         *
         */
        public void setProduct(Product value) {
            this.product = value;
        }

        /**
         * Gets the value of the productInfo property.
         *
         * @return
         *     possible object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.ProductInfo }
         *
         */
        public ProductInfo getProductInfo() {
            return productInfo;
        }

        /**
         * Sets the value of the productInfo property.
         *
         * @param value
         *     allowed object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.ProductInfo }
         *
         */
        public void setProductInfo(ProductInfo value) {
            this.productInfo = value;
        }

        /**
         * Gets the value of the contactPerson property.
         *
         * @return
         *     possible object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.ContactPerson }
         *
         */
        public ContactPerson getContactPerson() {
            return contactPerson;
        }

        /**
         * Sets the value of the contactPerson property.
         *
         * @param value
         *     allowed object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.ContactPerson }
         *
         */
        public void setContactPerson(ContactPerson value) {
            this.contactPerson = value;
        }

        /**
         * Gets the value of the visitPerson property.
         *
         * @return
         *     possible object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.VisitPerson }
         *
         */
        public VisitPerson getVisitPerson() {
            return visitPerson;
        }

        /**
         * Sets the value of the visitPerson property.
         *
         * @param value
         *     allowed object is
         *     {@link CreateComplexOrderRequestBody.OrderInfo.VisitPerson }
         *
         */
        public void setVisitPerson(VisitPerson value) {
            this.visitPerson = value;
        }

        /**
         * Gets the value of the orderQuantity property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOrderQuantity() {
            return orderQuantity;
        }

        /**
         * Sets the value of the orderQuantity property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOrderQuantity(String value) {
            this.orderQuantity = value;
        }

        /**
         * Gets the value of the orderPrice property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOrderPrice() {
            return orderPrice;
        }

        /**
         * Sets the value of the orderPrice property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOrderPrice(String value) {
            this.orderPrice = value;
        }

        /**
         * Gets the value of the orderStatus property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOrderStatus() {
            return orderStatus;
        }

        /**
         * Sets the value of the orderStatus property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOrderStatus(String value) {
            this.orderStatus = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "name",
                "mobile",
                "credentials",
                "credentialsType"
        })
        public static class ContactPerson {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String mobile;
            @XmlElement(required = true)
            protected String credentials;
            @XmlElement(required = true)
            protected String credentialsType;

            public ContactPerson() {
                super();
                this.name = "";
                this.mobile = "";
                this.credentials = "";
                this.credentialsType = "";
            }

            /**
             * Gets the value of the name property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the mobile property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getMobile() {
                return mobile;
            }

            /**
             * Sets the value of the mobile property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setMobile(String value) {
                this.mobile = value;
            }

            /**
             * Gets the value of the credentials property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCredentials() {
                return credentials;
            }

            /**
             * Sets the value of the credentials property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCredentials(String value) {
                this.credentials = value;
            }

            /**
             * Gets the value of the credentialsType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCredentialsType() {
                return credentialsType;
            }

            /**
             * Sets the value of the credentialsType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCredentialsType(String value) {
                this.credentialsType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="visitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "resourceId",
                "visitDate",
                "sellPrice",
                "productType"
        })
        public static class Product {

            @XmlElement(required = true)
            protected String resourceId;
            @XmlElement(required = true)
            protected String visitDate;
            @XmlElement(required = true)
            protected String sellPrice;
            @XmlElement(required = true)
            protected String productType;

            public Product() {
                super();
                this.resourceId = "";
                this.visitDate = "";
                this.sellPrice = "";
                this.productType = "";
            }

            /**
             * Gets the value of the resourceId property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getResourceId() {
                return resourceId;
            }

            /**
             * Sets the value of the resourceId property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setResourceId(String value) {
                this.resourceId = value;
            }

            /**
             * Gets the value of the visitDate property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getVisitDate() {
                return visitDate;
            }

            /**
             * Sets the value of the visitDate property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setVisitDate(String value) {
                this.visitDate = value;
            }

            /**
             * Gets the value of the sellPrice property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSellPrice() {
                return sellPrice;
            }

            /**
             * Sets the value of the sellPrice property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSellPrice(String value) {
                this.sellPrice = value;
            }

            /**
             * Gets the value of the productType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProductType() {
                return productType;
            }

            /**
             * Sets the value of the productType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProductType(String value) {
                this.productType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="timeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="areaId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="canrefundpart" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note4" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note6" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "itemId",
                "timeId",
                "areaId",
                "canrefundpart",
                "note1",
                "note2",
                "note3",
                "note4",
                "note5",
                "note6"
        })
        public static class ProductInfo {

            @XmlElement(required = true)
            protected String itemId;
            @XmlElement(required = true)
            protected String timeId;
            @XmlElement(required = true)
            protected String areaId;
            @XmlElement(required = true)
            protected String canrefundpart;
            @XmlElement(required = true)
            protected String note1;
            @XmlElement(required = true)
            protected String note2;
            @XmlElement(required = true)
            protected String note3;
            @XmlElement(required = true)
            protected String note4;
            @XmlElement(required = true)
            protected String note5;
            @XmlElement(required = true)
            protected String note6;

            public ProductInfo() {
                super();
                this.itemId = "";
                this.timeId = "";
                this.areaId = "";
                this.canrefundpart = "";
                this.note1 = "";
                this.note2 = "";
                this.note3 = "";
                this.note4 = "";
                this.note5 = "";
                this.note6 = "";
            }

            /**
             * Gets the value of the itemId property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getItemId() {
                return itemId;
            }

            /**
             * Sets the value of the itemId property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setItemId(String value) {
                this.itemId = value;
            }

            /**
             * Gets the value of the timeId property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTimeId() {
                return timeId;
            }

            /**
             * Sets the value of the timeId property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTimeId(String value) {
                this.timeId = value;
            }

            /**
             * Gets the value of the areaId property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAreaId() {
                return areaId;
            }

            /**
             * Sets the value of the areaId property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAreaId(String value) {
                this.areaId = value;
            }

            /**
             * Gets the value of the canrefundpart property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCanrefundpart() {
                return canrefundpart;
            }

            /**
             * Sets the value of the canrefundpart property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCanrefundpart(String value) {
                this.canrefundpart = value;
            }

            /**
             * Gets the value of the note1 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote1() {
                return note1;
            }

            /**
             * Sets the value of the note1 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote1(String value) {
                this.note1 = value;
            }

            /**
             * Gets the value of the note2 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote2() {
                return note2;
            }

            /**
             * Sets the value of the note2 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote2(String value) {
                this.note2 = value;
            }

            /**
             * Gets the value of the note3 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote3() {
                return note3;
            }

            /**
             * Sets the value of the note3 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote3(String value) {
                this.note3 = value;
            }

            /**
             * Gets the value of the note4 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote4() {
                return note4;
            }

            /**
             * Sets the value of the note4 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote4(String value) {
                this.note4 = value;
            }

            /**
             * Gets the value of the note5 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote5() {
                return note5;
            }

            /**
             * Sets the value of the note5 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote5(String value) {
                this.note5 = value;
            }

            /**
             * Gets the value of the note6 property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNote6() {
                return note6;
            }

            /**
             * Sets the value of the note6 property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNote6(String value) {
                this.note6 = value.replace("Ectrip", "yilvbao");
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="person" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "person"
        })
        public static class VisitPerson {

            protected List<Person> person;

            public VisitPerson() {
                super();
            }

            /**
             * Gets the value of the person property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the person property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPerson().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CreateComplexOrderRequestBody.OrderInfo.VisitPerson.Person }
             *
             *
             */
            public List<Person> getPerson() {
                if (person == null) {
                    person = new ArrayList<Person>();
                }
                return this.person;
            }

            public void setPerson(List<Person> person) {
                this.person = person;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="credentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="credentialsType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "name",
                    "credentials",
                    "credentialsType"
            })
            public static class Person {

                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String credentials;
                @XmlElement(required = true)
                protected String credentialsType;

                public Person() {
                    super();
                    this.name = "";
                    this.credentials = "";
                    this.credentialsType = "";
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the credentials property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCredentials() {
                    return credentials;
                }

                /**
                 * Sets the value of the credentials property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCredentials(String value) {
                    this.credentials = value;
                }

                /**
                 * Gets the value of the credentialsType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCredentialsType() {
                    return credentialsType;
                }

                /**
                 * Sets the value of the credentialsType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCredentialsType(String value) {
                    this.credentialsType = value;
                }

            }

        }

    }

}
