//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 08:17:05 下午 CST
//

package com.ectrip.ticket.cyt.model.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ectrip.tour._2014.qmrequestdataschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ectrip.tour._2014.qmrequestdataschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link NoticeOrderConsumedRequestBody }
     * 
     */
    public NoticeOrderConsumedRequestBody createNoticeOrderConsumedRequestBody() {
        return new NoticeOrderConsumedRequestBody();
    }

    /**
     * Create an instance of {@link CancelOrderRequestBody.OrderInfo }
     * 
     */
    public CancelOrderRequestBody.OrderInfo createCancelOrderRequestBodyOrderInfo() {
        return new CancelOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody.OrderInfo.ContactPerson }
     * 
     */
    public CreateOTOOrderRequestBody.OrderInfo.ContactPerson createCreateOrderRequestBodyOrderInfoContactPerson() {
        return new CreateOTOOrderRequestBody.OrderInfo.ContactPerson();
    }

    /**
     * Create an instance of {@link CheckPmsDataRequestBody }
     *
     */
    public CheckPmsDataRequestBody createCheckPmsDataRequestBody() {
        return new CheckPmsDataRequestBody();
    }

    /**
     * Create an instance of {@link CheckPmsDataRequestBody.PmsDatas }
     *
     */
    public CheckPmsDataRequestBody.PmsDatas createCheckPmsDataRequestBodyPmsDatas() {
        return new CheckPmsDataRequestBody.PmsDatas();
    }

    /**
     * Create an instance of {@link CheckPmsDataRequestBody.PmsDatas.PmsData }
     *
     */
    public CheckPmsDataRequestBody.PmsDatas.PmsData createCheckPmsDataRequestBodyPmsDatasPmsData() {
        return new CheckPmsDataRequestBody.PmsDatas.PmsData();
    }

    /**
     * Create an instance of {@link VerifyConsumeRequestBody }
     * 
     */
    public VerifyConsumeRequestBody createVerifyConsumeRequestBody() {
        return new VerifyConsumeRequestBody();
    }

    /**
     * Create an instance of {@link CancelOrderRequestBody }
     * 
     */
    public CancelOrderRequestBody createCancelOrderRequestBody() {
        return new CancelOrderRequestBody();
    }

    /**
     * Create an instance of {@link CancelOrderRequestBody.OrderInfo.VisitPerson }
     * 
     */
    public CancelOrderRequestBody.OrderInfo.VisitPerson createCancelOrderRequestBodyOrderInfoVisitPerson() {
        return new CancelOrderRequestBody.OrderInfo.VisitPerson();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody }
     * 
     */
    public CreateOTOOrderRequestBody createCreateOrderRequestBody() {
        return new CreateOTOOrderRequestBody();
    }

    /**
     * Create an instance of {@link PayOrderRequestBody }
     * 
     */
    public PayOrderRequestBody createPayOrderRequestBody() {
        return new PayOrderRequestBody();
    }

    /**
     * Create an instance of {@link VerifyConsumeRequestBody.OrderInfo }
     * 
     */
    public VerifyConsumeRequestBody.OrderInfo createVerifyConsumeRequestBodyOrderInfo() {
        return new VerifyConsumeRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link RequestBody }
     * 
     */
    public RequestBody createRequestBody() {
        return new RequestBody();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody.OrderInfo.VisitPerson }
     * 
     */
    public CreateOTOOrderRequestBody.OrderInfo.VisitPerson createCreateOrderRequestBodyOrderInfoVisitPerson() {
        return new CreateOTOOrderRequestBody.OrderInfo.VisitPerson();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody.OrderInfo.VisitPerson.Person }
     * 
     */
    public CreateOTOOrderRequestBody.OrderInfo.VisitPerson.Person createCreateOrderRequestBodyOrderInfoVisitPersonPerson() {
        return new CreateOTOOrderRequestBody.OrderInfo.VisitPerson.Person();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody.OrderInfo }
     * 
     */
    public CreateOTOOrderRequestBody.OrderInfo createCreateOrderRequestBodyOrderInfo() {
        return new CreateOTOOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link PayOrderRequestBody.OrderInfo }
     * 
     */
    public PayOrderRequestBody.OrderInfo createPayOrderRequestBodyOrderInfo() {
        return new PayOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link CreateOTOOrderRequestBody.OrderInfo.Product }
     * 
     */
    public CreateOTOOrderRequestBody.OrderInfo.Product createCreateOrderRequestBodyOrderInfoProduct() {
        return new CreateOTOOrderRequestBody.OrderInfo.Product();
    }

    /**
     * Create an instance of {@link CancelOrderRequestBody.OrderInfo.VisitPerson.Person }
     * 
     */
    public CancelOrderRequestBody.OrderInfo.VisitPerson.Person createCancelOrderRequestBodyOrderInfoVisitPersonPerson() {
        return new CancelOrderRequestBody.OrderInfo.VisitPerson.Person();
    }

    /**
     * Create an instance of {@link NoticeOrderConsumedRequestBody.OrderInfo }
     * 
     */
    public NoticeOrderConsumedRequestBody.OrderInfo createNoticeOrderConsumedRequestBodyOrderInfo() {
        return new NoticeOrderConsumedRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link QueryOrderRequestBody }
     * 
     */
    public QueryOrderRequestBody createQueryOrderRequestBody() {
        return new QueryOrderRequestBody();
    }

}
