//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 08:17:05 下午 CST
//


package com.ectrip.ticket.cyt.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 【OTO通提供】【订单】OTA获取订单信息（getOrderByOTA）
 * 赋初始值：已完成！
 * <p>Java class for QueryOrderRequestBody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="QueryOrderRequestBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMRequestDataSchema}RequestBody">
 *       &lt;sequence>
 *         &lt;element name="partnerOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryOrderRequestBody", propOrder = {
        "partnerOrderId"
})
public class QueryOrderRequestBody
        extends RequestBody
{

    @XmlElement(required = true)
    protected String partnerOrderId;

    public QueryOrderRequestBody() {
        super();
        this.partnerOrderId = "";
    }

    /**
     * Gets the value of the partnerOrderId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPartnerOrderId() {
        return partnerOrderId;
    }

    /**
     * Sets the value of the partnerOrderId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPartnerOrderId(String value) {
        this.partnerOrderId = value;
    }

}